/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was automatically generated by informer-gen

package internalversion

import (
	simple "github.com/u2takey/extend_k8s_example/pkg/apis/simple"
	internalclientset "github.com/u2takey/extend_k8s_example/pkg/client/clientset_generated/internalclientset"
	internalinterfaces "github.com/u2takey/extend_k8s_example/pkg/client/informers_generated/internalversion/internalinterfaces"
	internalversion "github.com/u2takey/extend_k8s_example/pkg/client/listers_generated/simple/internalversion"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	time "time"
)

// NginxAppInformer provides access to a shared informer and lister for
// NginxApps.
type NginxAppInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() internalversion.NginxAppLister
}

type nginxAppInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewNginxAppInformer constructs a new informer for NginxApp type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewNginxAppInformer(client internalclientset.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredNginxAppInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredNginxAppInformer constructs a new informer for NginxApp type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredNginxAppInformer(client internalclientset.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.Simple().NginxApps(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.Simple().NginxApps(namespace).Watch(options)
			},
		},
		&simple.NginxApp{},
		resyncPeriod,
		indexers,
	)
}

func (f *nginxAppInformer) defaultInformer(client internalclientset.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredNginxAppInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *nginxAppInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&simple.NginxApp{}, f.defaultInformer)
}

func (f *nginxAppInformer) Lister() internalversion.NginxAppLister {
	return internalversion.NewNginxAppLister(f.Informer().GetIndexer())
}
