/*
Copyright 2017 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was autogenerated by apiregister-gen. Do not edit it manually!

package simple

import (
	"fmt"
	"github.com/kubernetes-incubator/apiserver-builder/pkg/builders"
	"k8s.io/apimachinery/pkg/apis/meta/internalversion"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/runtime/schema"
	"k8s.io/apiserver/pkg/endpoints/request"
	"k8s.io/apiserver/pkg/registry/rest"
)

var (
	InternalNginxApp = builders.NewInternalResource(
		"nginxapps",
		"NginxApp",
		func() runtime.Object { return &NginxApp{} },
		func() runtime.Object { return &NginxAppList{} },
	)
	InternalNginxAppStatus = builders.NewInternalResourceStatus(
		"nginxapps",
		"NginxAppStatus",
		func() runtime.Object { return &NginxApp{} },
		func() runtime.Object { return &NginxAppList{} },
	)
	// Registered resources and subresources
	ApiVersion = builders.NewApiGroup("simple.example.com").WithKinds(
		InternalNginxApp,
		InternalNginxAppStatus,
	)

	// Required by code generated by go2idl
	AddToScheme        = ApiVersion.SchemaBuilder.AddToScheme
	SchemeBuilder      = ApiVersion.SchemaBuilder
	localSchemeBuilder = &SchemeBuilder
	SchemeGroupVersion = ApiVersion.GroupVersion
)

// Required by code generated by go2idl
// Kind takes an unqualified kind and returns a Group qualified GroupKind
func Kind(kind string) schema.GroupKind {
	return SchemeGroupVersion.WithKind(kind).GroupKind()
}

// Required by code generated by go2idl
// Resource takes an unqualified resource and returns a Group qualified GroupResource
func Resource(resource string) schema.GroupResource {
	return SchemeGroupVersion.WithResource(resource).GroupResource()
}

// +genclient
// +genclient
// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type NginxApp struct {
	metav1.TypeMeta
	metav1.ObjectMeta
	Spec   NginxAppSpec
	Status NginxAppStatus
}

type NginxAppSpec struct {
	Image    string
	Replicas *int32
}

type NginxAppStatus struct {
	Replicas int32
}

//
// NginxApp Functions and Structs
//
// +k8s:deepcopy-gen=false
type NginxAppStrategy struct {
	builders.DefaultStorageStrategy
}

// +k8s:deepcopy-gen=false
type NginxAppStatusStrategy struct {
	builders.DefaultStatusStorageStrategy
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

type NginxAppList struct {
	metav1.TypeMeta
	metav1.ListMeta
	Items []NginxApp
}

func (NginxApp) NewStatus() interface{} {
	return NginxAppStatus{}
}

func (pc *NginxApp) GetStatus() interface{} {
	return pc.Status
}

func (pc *NginxApp) SetStatus(s interface{}) {
	pc.Status = s.(NginxAppStatus)
}

func (pc *NginxApp) GetSpec() interface{} {
	return pc.Spec
}

func (pc *NginxApp) SetSpec(s interface{}) {
	pc.Spec = s.(NginxAppSpec)
}

func (pc *NginxApp) GetObjectMeta() *metav1.ObjectMeta {
	return &pc.ObjectMeta
}

func (pc *NginxApp) SetGeneration(generation int64) {
	pc.ObjectMeta.Generation = generation
}

func (pc NginxApp) GetGeneration() int64 {
	return pc.ObjectMeta.Generation
}

// Registry is an interface for things that know how to store NginxApp.
// +k8s:deepcopy-gen=false
type NginxAppRegistry interface {
	ListNginxApps(ctx request.Context, options *internalversion.ListOptions) (*NginxAppList, error)
	GetNginxApp(ctx request.Context, id string, options *metav1.GetOptions) (*NginxApp, error)
	CreateNginxApp(ctx request.Context, id *NginxApp) (*NginxApp, error)
	UpdateNginxApp(ctx request.Context, id *NginxApp) (*NginxApp, error)
	DeleteNginxApp(ctx request.Context, id string) (bool, error)
}

// NewRegistry returns a new Registry interface for the given Storage. Any mismatched types will panic.
func NewNginxAppRegistry(sp builders.StandardStorageProvider) NginxAppRegistry {
	return &storageNginxApp{sp}
}

// Implement Registry
// storage puts strong typing around storage calls
// +k8s:deepcopy-gen=false
type storageNginxApp struct {
	builders.StandardStorageProvider
}

func (s *storageNginxApp) ListNginxApps(ctx request.Context, options *internalversion.ListOptions) (*NginxAppList, error) {
	if options != nil && options.FieldSelector != nil && !options.FieldSelector.Empty() {
		return nil, fmt.Errorf("field selector not supported yet")
	}
	st := s.GetStandardStorage()
	obj, err := st.List(ctx, options)
	if err != nil {
		return nil, err
	}
	return obj.(*NginxAppList), err
}

func (s *storageNginxApp) GetNginxApp(ctx request.Context, id string, options *metav1.GetOptions) (*NginxApp, error) {
	st := s.GetStandardStorage()
	obj, err := st.Get(ctx, id, options)
	if err != nil {
		return nil, err
	}
	return obj.(*NginxApp), nil
}

func (s *storageNginxApp) CreateNginxApp(ctx request.Context, object *NginxApp) (*NginxApp, error) {
	st := s.GetStandardStorage()
	obj, err := st.Create(ctx, object, nil, true)
	if err != nil {
		return nil, err
	}
	return obj.(*NginxApp), nil
}

func (s *storageNginxApp) UpdateNginxApp(ctx request.Context, object *NginxApp) (*NginxApp, error) {
	st := s.GetStandardStorage()
	obj, _, err := st.Update(ctx, object.Name, rest.DefaultUpdatedObjectInfo(object), nil, nil)
	if err != nil {
		return nil, err
	}
	return obj.(*NginxApp), nil
}

func (s *storageNginxApp) DeleteNginxApp(ctx request.Context, id string) (bool, error) {
	st := s.GetStandardStorage()
	_, sync, err := st.Delete(ctx, id, nil)
	return sync, err
}
